jobs:
  lock-and-delete:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: lock issue and delete comment
      uses: pansong291/issue-interceptor-action@main
      with:
        test-regex: ${{ secrets.REGEX_ISSUE_INTERCEPTOR }}
name: Lock Issue And Delete Comment
on:
  repository_dispatch:
    types: trigger-ga___lock-issue-and-delete-comment.yml
